import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Slab, Source_Sans_3 } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { QueryProvider } from "@/components/query-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const sourceSans3Heading = Source_Sans_3({subsets:['latin'],variable:'--font-heading'});

const robotoSlab = Roboto_Slab({subsets:['latin'],variable:'--font-serif'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-serif", robotoSlab.variable, sourceSans3Heading.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className='border-b border-border bg-background'>
            <div className='mx-auto flex w-full max-w-[1600px] items-center gap-4 px-4 py-3 text-sm sm:px-6 xl:px-8'>
              <Link className='font-medium hover:underline' href='/'>
                Orders
              </Link>
              <Link className='font-medium hover:underline' href='/categories'>
                Categories
              </Link>
              <Link className='font-medium hover:underline' href='/allocation'>
                Allocation
              </Link>
              <Link className='font-medium hover:underline' href='/movers'>
                Movers
              </Link>
              <Link
                className='font-medium hover:underline'
                href='/risk-mappings'
              >
                Risk mappings
              </Link>
            </div>
          </nav>
          <QueryProvider>{children}</QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
